#!/usr/bin/env bash
## uwuLuks - LUKS Encrypted Loopback

## debug check
# if UWU_DEBUG is set in the environment, then debug mode is enabled
if [[ -n "$UWU_DEBUG" ]]; then
  set -x
fi

function usage() {
    echo "uwuLuks - LUKS Encrypted Loopback Storage"
    echo "Usage: uwuluks <action> <params>"
    echo "Actions:"
    echo "    -h, --help                       Show this"
    echo "    -v, --version                    Show version"
    echo "    -m, --mount <name> [mountpoint]  Mount LUKS encrypted loopback"
    echo "    -u, --unmount <id>               Unmount LUKS encrypted loopback"
    echo "    -d, --delete <name>              Delete LUKS encrypted loopback"
    echo "    -c, --create <name> <size> [fs]  Create LUKS encrypted loopback"
    echo "    -l, --list                       List LUKS encrypted loopbacks"
    echo "        --unmount-unsafe <id>        Unsafely unmount LUKS encrypted loopback (Not recommended)"
}

function succ() {
    # err() but green
    export msg="$1"
    echo -e "\e[32mSuccess:\e[0m $msg"
    return 0 
}

function info() {
    # err() but blue
    export msg="$1"
    echo -e "\e[34mInfo:\e[0m $msg"
}

function err() {
    # Show error message and exit
    export msg="$1"
    echo -e "\e[31mError:\e[0m $msg"
    exit 1
}

function warn() {
    # err() but yellow
    export msg="$1"
    echo -e "\e[33mWarning:\e[0m $msg"
}

function create_ll() {
    # Create a LUKS encrypted loopback device
    # <name> - Name of image
    # <size> - Size of image in MB
    # <fs> - Filesystem (optional)
    # Valid filesystem options:
    # - ext4 (default)
    # - fat32
    # - xfs
    # - f2fs
    # - ntfs
    # - btrfs
    # - exfat
    # - custom
	
    export name="$1"
    export size="$2"
    export fs="$3"

    # check if FS is specified
    if [ -z "$fs" ]; then
        fs="ext4"
    fi

    # check if FS is valid
    if [ "$fs" != "ext4" ] && [ "$fs" != "fat32" ] && [ "$fs" != "btrfs" ] && [ "$fs" != "exfat" ] && [ "$fs" != "xfs" ] && [ "$fs" != "f2fs" ] && [ "$fs" != "ntfs" ]; then 
        err "Invalid filesystem: $fs" 1
    fi
    
    # check if image already exists
    if [ -f "$HOME/.local/share/lel/$name.img" ]; then
        err "Image already exists: $name.img" 1
    fi

    # check if name is valid
    # invalid characters: space, tab, newline, /, \
    export $name=$(echo "$name" | sed -e 's/[ \t\n\/\\]//g')
    if [ -z "$name" ]; then
	err "Invalid name: $name"
    fi

    ###
    # This *should* check if the size is valid,
    # but for whatever reason, it doesn't.
    # therefore, we dont check anything.
    # If it's not valid, it will fail later anyways.
    # If it breaks, it breaks. Its the user's fault.
    ###

    #export regex_size="^[1-9][0-9]+[KMGTP]?$"
    # check if size is valid
    #if ! [[ "$size" =~ "$regex_size" ]]; then
    #	err "Invalid size: $size"
    #fi


    # create the image
    info "Creating image: $name.img"
    info "Size: $size"
    info "Filesystem: $fs"
    if [ "$fs" == "ntfs" ]; then
	    warn "NTFS may or may not work. Please test."
	    read -rp "Press any key to continue..."
    fi

    if [ ! -d "$HOME/.local/share/lel" ]; then
        mkdir -p "$HOME/.local/share/lel"
    fi
    cd "$HOME/.local/share/lel" 2> /dev/null || err "Failed to change directory to ~/.local/share/lel" 1
    truncate -s "$size" "$name.img" 2> /dev/null || err "Failed to create image" 1
    cryptsetup luksFormat "$name.img" 2> /dev/null || err "Failed to encrypt image" 1
    sudo cryptsetup luksOpen "$name.img" "$name" 2> /dev/null || err "Failed to open image" 1

    # if $fs is custom, ask for the custom fs command
    if [ "$fs" == "custom" ]; then
        info "Selected custom filesystem. Enter command to format the image (with \$name as the image)"
        read -rp "> " fs_cmd
    fi

    # if $fs is not custom, use the default fs command
    sudo mkfs."$fs" /dev/mapper/"$name" 2> /dev/null || err "Failed to create filesystem" 1

    # if $fs is custom, use the custom fs command (if set)
    if [ $fs == "custom" ]; then
        eval "$fs_cmd" 2> /dev/null || err "Failed to format image" 1
    fi
    mkdir -p "$name"-mount
    sudo mount /dev/mapper/"$name" "$name"-mount 2> /dev/null || err "Failed to mount filesystem" 1

    # fix permissions
    sudo chown -R "$USER":"$USER" "$name"-mount 2> /dev/null || err "Failed to change ownership of mountpoint" 1
    sudo chmod -R 700 "$name"-mount 2> /dev/null || err "Failed to change permissions of mountpoint" 1
    sudo chmod -R 700 "$name".img 2> /dev/null || err "Failed to change permissions of image" 1
    succ "Created LUKS encrypted loopback device: ~/.local/share/lel/$name.img (mountpoint: $HOME/.local/share/lel/$name-mount)"
}

function mount_ll() {
    # Mount a LUKS encrypted loopback device
    # <name> - Name of image
    # <mountpoint> - Mountpoint (by default ~/.local/share/lel/<name>-mount)

    export name="$1"
    export mountpoint="$2"

    if [ ! -f "$HOME/.local/share/lel/$name.img" ]; then
        err "Image does not exist: $name.img" 1
    fi
    if [ ! -d "$mountpoint" ]; then
        err "Mountpoint is not a directory: $mountpoint" 1
    fi
    if [ "$(ls -A "$mountpoint")" ]; then
        err "Mountpoint is not empty: $mountpoint" 1
    fi
    # shellcheck disable=SC2143
    if [ -n "$(mount | grep "$mountpoint")" ]; then
        err "Mountpoint is already mounted: $mountpoint" 1
    fi
    sudo cryptsetup luksOpen "$HOME/.local/share/lel/$name.img" "$name" 2> /dev/null || err "Failed to open image" 1
    sudo mount /dev/mapper/"$name" "$mountpoint" 2> /dev/null || err "Failed to mount image" 1
    succ "Mounted LUKS encrypted loopback device: $name.img (mountpoint: $mountpoint)"
}

function delete_ll() {
    # Delete a LUKS encrypted loopback device
    # <name> - Name of image

    export name="$1"

    if [ ! -f "$HOME/.local/share/lel/$name.img" ]; then
        err "Image does not exist: $name.img" 1
    fi
    warn "Are you sure you want to delete $name? This action is not reversable!"
    read -p "Confirmation [y/N]: " -n 1 -r
    echo
    if [ ! $REPLY == "y" ] && [ ! $REPLY == "Y" ]; then
        err "Aborted" 1
    fi

    # if image is mounted, run the below 2 commands
    if [ -n "$(mount | grep "$HOME/.local/share/lel/$name-mount")" ]; then
	sudo umount "$HOME/.local/share/lel/$name-mount" 2> /dev/null || err "Failed to unmount image" 1
	sudo cryptsetup luksClose "$name" 2> /dev/null || err "Failed to close image" 1
    fi

    shred -fvz -n 10 "$HOME/.local/share/lel/$name.img" || warn "Failed to overwrite image for secure deletion"
    rm "$HOME/.local/share/lel/$name.img" 2> /dev/null || err "Failed to delete image" 1
    rmdir "$HOME/.local/share/lel/$name-mount" || warn "Failed to delete mountpoint"
    succ "Deleted LUKS encrypted loopback device: $name.img"
}

function unmount_ll() {
    # Unmount a LUKS encrypted loopback device
    # <id> - either name of image or mountpoint
    # steps:

    export id="$1"

    if [ ! -f "$HOME/.local/share/lel/$id.img" ] && [ ! -d "$HOME/.local/share/lel/$id-mount" ]; then
        err "Image or mountpoint does not exist: $id" 1
    fi
    sudo umount "$id" 2> /dev/null || err "Failed to unmount image" 1
    sudo cryptsetup luksClose "$id" 2> /dev/null || err "Failed to close image" 1
    succ "Unmounted LUKS encrypted loopback device: $id"
}

function unmount_unsafe() {
    # Same as above, but unmount with `--lazy --force`
    # asks for confirmation
    # <id> - either name of image or mountpoint

    export id="$1"

    if [ ! -f "$HOME/.local/share/lel/$id.img" ] && [ ! -d "$HOME/.local/share/lel/$id-mount" ]; then
        err "Image or mountpoint does not exist: $id" 1
    fi
    warn "Are you sure you want to unsafely unmount $id? This action may corrupt data!"
    read -p "Confirmation [y/N]: " -n 1 -r
    echo
    if [ ! $REPLY == "y" ] && [ ! $REPLY == "Y" ]; then
        err "Aborted" 1
    fi
    info "Unsafely unmounting $id"
    sudo umount --lazy --force "$id" 2> /dev/null || err "Failed to unmount image" 1
    sudo cryptsetup luksClose "$id" 2> /dev/null || err "Failed to close image" 1
    succ "Unmounted LUKS encrypted loopback device: $id"
}

function list_ll() {
    # List all LEL images
    # only print images matching this regex:
    # /^.+\.img$/gm

    cd "$HOME/.local/share/lel" 2> /dev/null || err "Failed to change to directory: $HOME/.local/share/lel" 1
    info "All LEL images:"
    find . -regex '^.+\.img$' | sed -e 's+./++g'
}

## Main

if [ "$#" -eq 0 ]; then
    usage
elif [ "$#" -eq 1 ]; then
    case "$1" in
        -h|--help)
            usage
            ;;
        -v|--version)
	    export VERSION="0.1.2-github"
            info "uwuLuks - LUKS Encrypted Loopback Storage"
            info "Version: $VERSION"
            info "Author: Breadtard#1937"
	    info "Source: https://github.com/breadtard/uwuTools/"
            ;;
        -l|--list)
            list_ll
            ;;
        *)
            err "Invalid or missing argument"
            usage
            ;;
    esac
elif [ "$#" -ge 2 ]; then
    case "$1" in
        -m|--mount)
            mount_ll "$2" "$3"
            ;;
        -u|--unmount)
            unmount_ll "$2"
            ;;
        -d|--delete)
            delete_ll "$2"
            ;;
        -c|--create)
            create_ll "$2" "$3" "$4"
            ;;
        --unmount-unsafe)
            unmount_unsafe "$2"
            ;;
        *)
            err "Invalid argument"
            usage
            ;;
    esac
else
    err "Invalid argument"
    usage
fi
